# version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'afvalical'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'afvalical'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'm0nk3y'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Polle007'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  app:
    build: ./
    links:
      - mysql
    ports:
      - 3000:3000
    command:
      sh -c 'ruby app.rb' 
# Names our volume
volumes:
  my-db:
