version: '3.1'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'DBASE_NAME_GOES_HERE'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'DBASE_USER_GOES_HERE'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'somerandompassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'somerandomrootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  app:
    build: ./
    volumes:
      - .:/app
    links:
      - mysql
    ports:
      - 3000:3000
    command:
      sh -c 'ruby app.rb' 
# Names our volume
volumes:
  my-db:
